When deploying this overrites.

new:
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - shareameal

on:
  push:
    branches:
      - Test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'shareameal'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5BBDF786216A48A6B655CC60A8978DF9 }}
          package: .

Old.
name: Testing and deployment

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: shareameal # set this to your application's name
  RESOURCE_GROUP: shareameal_group # set this to your Azure Resource Group's name
  MYSQL_ROOT_PASSWORD: root 
  DB_HOST: '127.0.0.1'
  DB_PORT: '3306'
  DB_DATABASE: share_a_meal
  DB_USER: root
  DB_PASSWORD: root

jobs:
  integrationtests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - '3306'
    steps:
      - uses: actions/checkout@main

      - name: Start MySQL connection from host
        run: |
          sudo /etc/init.d/mysql start
          sudo apt-get install -y mysql-client
          mysql -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"
          mysql -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE ${{env.DB_DATABASE}};"

      - name: Import database script
        run: |
          mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} < share-a-meal.sql
          mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} -e "SHOW TABLES;"

      - name: npm install
        run: |
          npm install

      - name: npm test
        run: |
          npm test -- --DB_PASSWORD {{env.MYSQL_ROOT_PASSWORD}} --DB_USER root --DB_NAME ${{env.DB_DATABASE}}

  Azure-deploy:
    needs: integrationtests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production' # change this if you have a different Slot name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} # set this with your Azure Publish Profile Secret
          package: '.' # path to your application's root
